# Generated by Django 4.2.29 on 2026-04-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='incentive',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='problem_and_goal',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('class', 'Proyecto de clase'), ('thesis', 'Tesis o Tesina'), ('hackathon', 'Concurso o Hackathon'), ('startup', 'Emprendimiento propio')], default='class', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='stage',
            field=models.CharField(choices=[('idea', '💡 Solo es una idea (Fase 0)'), ('planning', '📝 En planeación / Diseño (Fase 1)'), ('prototype', '🛠️ Prototipo iniciado (Fase 2)'), ('active', '🚀 En desarrollo activo (Fase 3)')], default='class', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='target_careers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='vacancies',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='work_mode',
            field=models.CharField(choices=[('remote', '100% Remoto'), ('onsite', 'Presencial (En campus)'), ('hybrid', 'Híbrido')], default='idea', max_length=20),
            preserve_default=False,
        ),
    ]
