# Generated by Django 4.2.29 on 2026-04-30 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_project_application_deadline_project_incentive_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='posts/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'doc', 'docx'])], verbose_name='Archivo adjunto'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.CharField(choices=[('idea', 'Solo es una idea (Fase 0)'), ('planning', 'En planeación / Diseño (Fase 1)'), ('prototype', 'Prototipo iniciado (Fase 2)'), ('active', 'En desarrollo activo (Fase 3)')], max_length=20),
        ),
    ]
