# Generated by Django 4.2.29 on 2026-05-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='cover_photo',
            field=models.ImageField(blank=True, default='cover_photos/default_cover.png', upload_to='cover_photos/'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default_user.png', upload_to='profile_pics/'),
        ),
    ]
