# Generated by Django 4.2.29 on 2026-05-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_studentuser_cover_photo_studentuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='cover_photos/'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
